import './js/elements.js';
import './js/header.js';
import './js/hero.js';
import './js/abouts.js';
import './js/project.js';
import './js/questions.js';
import './js/covers.js';
import './js/reviews.js';
import './js/work-together.js';
